Update W3.yml

diff --git a/.github/workflows/W3.yml b/.github/workflows/W3.yml
--- a/.github/workflows/W3.yml
+++ b/.github/workflows/W3.yml
@@ -41,6 +41,15 @@ jobs:
          run: |
            echo "test step 1"
            sleep 5    
+  notification:
+     runs-on: ubuntu-latest
+     needs: build
+     if: ${{ needs.build.result == 'failure' || failure() }}
+     steps:
+       - name: notify
+         run: |
+           echo "Build step got failed"
+           sleep 10  
   deploy:
      runs-on: ubuntu-latest
      if: ${{ always () }}
